"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import NomiNav from "../components/NomiNav";
import type { CommunityLook, CommunityPiece } from "../components/ShareToExploreModal";
import { OCCASION_GROUPS, toTagSlug, normalizeTag } from "../components/ShareToExploreModal";
import ItemThumbnail from "../components/ItemThumbnail";
import trendsRaw from "../data/trends.json";
import type { PinterestBoard } from "../api/pinterest/boards/route";
import type { PinterestPin } from "../api/pinterest/boards/[boardId]/pins/route";

// ─── Trends (static, generated by scripts/generate-trends.mjs) ───────────────

type TrendSource = { name: string; url: string | null };
type TrendItem   = { title: string; summary: string; sources: TrendSource[] };
type TrendsFile  = { generatedAt: string | null; trends: TrendItem[] };

const { generatedAt: trendsGeneratedAt, trends } = trendsRaw as TrendsFile;

function formatTrendDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

// ─── Constants ────────────────────────────────────────────────────────────────

const FILTER_TABS = ["All", "OOTD", "Going out", "Events", "Weddings", "Work", "Secondhand"] as const;
type FilterTab = typeof FILTER_TABS[number];

function tabLabel(tab: FilterTab): string {
  if (tab === "All") return "All";
  const camel = tab.replace(/\s+(.)/g, (_, c) => c.toUpperCase());
  return `#${camel}`;
}

const _g = (label: string) =>
  OCCASION_GROUPS.find(g => g.label === label)!.options.map(normalizeTag);

const OCCASION_FILTER: Record<string, string[]> = {
  "OOTD":       _g("Everyday"),
  "Going out":  _g("Going out"),
  "Events":     _g("Events"),
  "Weddings":   _g("Weddings"),
  "Work":       _g("Work"),
  "Secondhand": _g("Secondhand"),
};

const OCCASION_SLUG_SET = new Set(
  OCCASION_GROUPS.flatMap(g => g.options.map(normalizeTag))
);

function slugToFilterTab(slug: string): FilterTab | null {
  const norm = normalizeTag(slug);
  for (const [tab, slugs] of Object.entries(OCCASION_FILTER)) {
    if (slugs.includes(norm)) return tab as FilterTab;
  }
  return null;
}

const PLACEHOLDER_COLORS = ["#f0ede8", "#ece9e4", "#e8e4dd", "#ede9e3"];

// ─── Helpers ─────────────────────────────────────────────────────────────────

function timeAgo(ts: number): string {
  const d = Date.now() - ts;
  const m = Math.floor(d / 60000);
  if (m < 2)  return "just now";
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  const days = Math.floor(h / 24);
  if (days < 7) return `${days}d ago`;
  return new Date(ts).toLocaleDateString([], { month: "short", day: "numeric" });
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function ExplorePage() {
  const router = useRouter();
  const [looks,     setLooks]     = useState<CommunityLook[]>([]);
  const [savedIds,  setSavedIds]  = useState<Set<string>>(new Set());
  const [activeTab, setActiveTab] = useState<FilterTab>("All");
  const [selected,  setSelected]  = useState<CommunityLook | null>(null);
  const [query,     setQuery]     = useState("");
  const feedRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const communityLooks: CommunityLook[] = JSON.parse(localStorage.getItem("nomi_community_looks") ?? "[]");

    // One-time migration: old community looks were saved before `look.images` was added to the
    // schema and only have the single `look.image` field. Find each one's corresponding saved
    // look by matching piece names and pull the real per-item image URLs from there.
    type SavedItem = { name?: string; image?: string; isOriginal?: boolean };
    type SavedLookRef = { items: SavedItem[] };
    const savedLooks: SavedLookRef[] = JSON.parse(localStorage.getItem("nomi_saved_looks") ?? "[]");

    let anyPatched = false;
    const patched = communityLooks.map(look => {
      if (look.images?.length) return look; // already has images — nothing to do

      // Find a saved look whose non-original items match this community look's pieces exactly
      const matched = savedLooks.find(sl => {
        const saveMatchNames = sl.items.filter(i => !i.isOriginal).map(i => i.name ?? "");
        return look.pieces.length > 0 &&
               look.pieces.length <= saveMatchNames.length &&
               look.pieces.every(p => saveMatchNames.includes(p.name));
      });
      if (!matched) return look;

      const originalImg = matched.items.find(i => i.isOriginal)?.image;
      const matchImgs   = look.pieces
        .map(p => matched.items.find(i => !i.isOriginal && i.name === p.name)?.image)
        .filter((img): img is string => !!img);

      const allImgs = [originalImg, ...matchImgs].filter((img): img is string => !!img);
      if (!allImgs.length) return look;

      anyPatched = true;
      return { ...look, images: allImgs };
    });

    if (anyPatched) {
      localStorage.setItem("nomi_community_looks", JSON.stringify(patched));
    }

    setLooks(patched);
    setSavedIds(new Set(JSON.parse(localStorage.getItem("nomi_community_saved") ?? "[]")));
  }, []);

  const feed = useMemo(() => {
    let list = [...looks];
    if (activeTab === "All") {
      list.sort((a, b) => b.sharedAt - a.sharedAt);
    } else {
      const match = OCCASION_FILTER[activeTab] ?? [];
      list = list.filter(l => l.tags.some(t => match.includes(normalizeTag(t))));
    }
    if (query.trim()) {
      const q    = query.toLowerCase();
      const qTag = q.startsWith("#") ? q : `#${q}`;
      list = list.filter(l =>
        l.caption.toLowerCase().includes(q) ||
        l.tags.some(t => t.toLowerCase().includes(q) || t.toLowerCase() === qTag) ||
        l.pieces.some(p => p.name.toLowerCase().includes(q))
      );
    }
    return list;
  }, [looks, activeTab, query]);

  const trendingTags = useMemo(() => {
    const counts: Record<string, number> = {};
    looks.forEach(l => {
      l.tags.forEach(t => {
        const n = normalizeTag(t);
        if (n) counts[n] = (counts[n] ?? 0) + 1;
      });
    });
    return Object.entries(counts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 10)
      .map(([tag]) => tag);
  }, [looks]);

  const vibeTiles = useMemo(() => {
    return OCCASION_GROUPS.flatMap(g => [...g.options])
      .map(opt => {
        const slug = normalizeTag(opt);
        const cover = looks
          .filter(l => l.tags.some(t => normalizeTag(t) === slug) && !!l.image)
          .sort((a, b) => b.sharedAt - a.sharedAt)[0];
        return cover ? { label: opt, slug, image: cover.image! } : null;
      })
      .filter((t): t is NonNullable<typeof t> => t !== null);
  }, [looks]);

  function handleVibeTap(slug: string) {
    const tab = slugToFilterTab(slug);
    if (!tab) return;
    setActiveTab(tab);
    setTimeout(() => feedRef.current?.scrollIntoView({ behavior: "smooth" }), 50);
  }


  function handleSave(look: CommunityLook, e: React.MouseEvent) {
    e.stopPropagation();
    const isSaved = savedIds.has(look.id);
    setSavedIds(prev => {
      const next = new Set(prev);
      if (isSaved) {
        next.delete(look.id);
      } else {
        next.add(look.id);
        // Increment savedCount on the stored look
        const all: CommunityLook[] = JSON.parse(localStorage.getItem("nomi_community_looks") ?? "[]");
        const updated = all.map(l => l.id === look.id ? { ...l, savedCount: l.savedCount + 1 } : l);
        localStorage.setItem("nomi_community_looks", JSON.stringify(updated));
        setLooks(updated);
        // Update taste profile silently
        updateTasteProfile(look);
      }
      localStorage.setItem("nomi_community_saved", JSON.stringify([...next]));
      return next;
    });
  }

  function updateTasteProfile(look: CommunityLook) {
    try {
      const profile = JSON.parse(localStorage.getItem("nomi_taste_profile") ?? "{}");
      if (!profile.aesthetics) profile.aesthetics = {};
      look.tags.forEach(tag => {
        profile.aesthetics[tag] = (profile.aesthetics[tag] ?? 0) + 1;
      });
      if (!profile.savedCategories) profile.savedCategories = {};
      look.pieces.forEach(piece => {
        if (piece.category)
          profile.savedCategories[piece.category] = (profile.savedCategories[piece.category] ?? 0) + 1;
      });
      localStorage.setItem("nomi_taste_profile", JSON.stringify(profile));
    } catch { /* ignore */ }
  }

  return (
    <>
      <div style={{ minHeight: "100vh", background: "#fff", display: "flex", flexDirection: "column", alignItems: "center" }}>
        <div style={{ width: "100%", maxWidth: "420px" }}>

          {/* ── Sticky header ── */}
          <div style={{ position: "sticky", top: 0, background: "#fff", zIndex: 10 }}>
            <div style={{ padding: "20px 16px 10px" }}>
              <h1 style={{ fontSize: "22px", fontWeight: 600, letterSpacing: "-0.5px", marginBottom: "12px" }}>Explore</h1>
              {/* Search */}
              <div style={{ position: "relative" }}>
                <div style={{ position: "absolute", left: "13px", top: "50%", transform: "translateY(-50%)", color: "#aaa", pointerEvents: "none", lineHeight: 0 }}>
                  <SearchIcon />
                </div>
                <input
                  type="text" placeholder="Search looks, occasions, items..."
                  value={query} onChange={e => setQuery(e.target.value)}
                  style={{ width: "100%", padding: "11px 36px 11px 38px", borderRadius: "14px", border: `1.5px solid ${query ? "#000" : "#e8e8e8"}`, fontSize: "14px", color: "#000", background: "#f7f6f3", outline: "none", transition: "border-color 0.15s", boxSizing: "border-box" } as React.CSSProperties}
                />
                {query && (
                  <button onClick={() => setQuery("")} style={{ position: "absolute", right: "12px", top: "50%", transform: "translateY(-50%)", background: "none", border: "none", cursor: "pointer", color: "#aaa", lineHeight: 0, padding: 0 }}>
                    <XIcon />
                  </button>
                )}
              </div>
            </div>
            <div style={{ display: "flex", gap: "8px", overflowX: "auto", paddingLeft: "16px", paddingRight: "16px", paddingBottom: "12px", scrollbarWidth: "none" }}>
              {FILTER_TABS.map(tab => {
                const on = activeTab === tab;
                return (
                  <button key={tab} onClick={() => setActiveTab(tab)} style={{
                    flexShrink: 0, padding: "7px 16px", borderRadius: "99px", border: "none",
                    background: on ? "#c9a96e" : "#f0ede8",
                    color: on ? "#fff" : "#6b6b6b",
                    fontSize: "13px", fontWeight: on ? 600 : 400,
                    cursor: "pointer", whiteSpace: "nowrap",
                    transition: "background 0.15s, color 0.15s",
                  }}>
                    {tabLabel(tab)}
                  </button>
                );
              })}
            </div>
            {trendingTags.length > 0 && (
              <div>
                <p style={{ padding: "8px 16px 4px", fontSize: "10px", fontWeight: 600, color: "#bbb", letterSpacing: "0.6px", textTransform: "uppercase" }}>Trending tags</p>
                <div style={{ display: "flex", gap: "6px", overflowX: "auto", paddingLeft: "16px", paddingRight: "16px", paddingBottom: "10px", scrollbarWidth: "none" } as React.CSSProperties}>
                  {trendingTags.map(tag => {
                    const active = query.toLowerCase() === tag.toLowerCase();
                    return (
                      <button key={tag} onClick={() => setQuery(active ? "" : tag)} style={{
                        flexShrink: 0, padding: "5px 12px", borderRadius: "99px",
                        border: `1px solid ${active ? "#c9a96e" : "#e0dbd4"}`,
                        background: "none", cursor: "pointer", whiteSpace: "nowrap",
                        color: active ? "#c9a96e" : "#999",
                        fontSize: "12px", fontWeight: active ? 500 : 400,
                        transition: "color 0.15s, border-color 0.15s",
                        fontFamily: "inherit",
                      }}>
                        {tag}
                      </button>
                    );
                  })}
                </div>
              </div>
            )}
            <div style={{ height: "1px", background: "#ebebeb" }} />
          </div>

          {/* ── What's Hot ── */}
          {activeTab === "All" && trends.length > 0 && (
            <div style={{ padding: "16px 0 4px" }}>
              <div style={{ padding: "0 16px 10px" }}>
                <p style={{ fontSize: "13px", fontWeight: 600, color: "#000", letterSpacing: "-0.2px" }}>What&apos;s Hot</p>
                <p style={{ fontSize: "11px", color: "#bbb", marginTop: "2px" }}>
                  Weekly fashion digest{trendsGeneratedAt ? ` · Updated ${formatTrendDate(trendsGeneratedAt)}` : ""}
                </p>
              </div>
              <div style={{ display: "flex", gap: "10px", overflowX: "auto", paddingLeft: "16px", paddingRight: "16px", paddingBottom: "4px", scrollbarWidth: "none" } as React.CSSProperties}>
                {trends.map((trend, i) => (
                  <div key={i} style={{
                    flexShrink: 0, width: "calc(82% - 8px)",
                    borderRadius: "14px",
                    border: "1px solid #ede8e0", borderLeft: "3px solid #c9a96e",
                    background: "#faf7f3",
                    padding: "14px 14px 14px 13px",
                  }}>
                    <p style={{ fontSize: "13px", fontWeight: 600, color: "#000", letterSpacing: "-0.2px", lineHeight: 1.3 }}>{trend.title}</p>
                    <p style={{ fontSize: "12px", color: "#555", lineHeight: 1.65, marginTop: "7px" }}>{trend.summary}</p>
                    <p style={{ fontSize: "11px", color: "#bbb", marginTop: "9px" }}>
                      via{" "}
                      {trend.sources.map((src, j) => (
                        <span key={j}>
                          {j > 0 && ", "}
                          {src.url
                            ? <a href={src.url} target="_blank" rel="noopener noreferrer" style={{ color: "#bbb", textDecoration: "underline", textUnderlineOffset: "2px" }}>{src.name}</a>
                            : src.name
                          }
                        </span>
                      ))}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* ── Browse by vibe ── */}
          {activeTab === "All" && vibeTiles.length > 0 && (
            <div style={{ padding: "16px 16px 0" }}>
              <p style={{ fontSize: "13px", fontWeight: 600, color: "#000", letterSpacing: "-0.2px", marginBottom: "10px" }}>Browse by vibe</p>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px", marginBottom: "8px" }}>
                {vibeTiles.map(tile => (
                  <VibeTile key={tile.slug} label={tile.label} image={tile.image} onTap={() => handleVibeTap(tile.slug)} />
                ))}
              </div>
            </div>
          )}

          {/* ── Pinterest import ── */}
          {activeTab === "All" && <PinterestSection />}

          {/* ── Feed ── */}
          {looks.length === 0 ? (
            <EmptyState onShare={() => router.push("/saved")} />
          ) : feed.length === 0 ? (
            <div style={{ display: "flex", flexDirection: "column", alignItems: "center", padding: "60px 32px", textAlign: "center", gap: "10px" }}>
              <p style={{ fontSize: "15px", color: "#555" }}>No looks found for that search.</p>
              <button onClick={() => setQuery("")} style={{ background: "none", border: "none", cursor: "pointer", color: "#c9a96e", fontSize: "14px", fontWeight: 500, padding: 0 }}>Clear search</button>
            </div>
          ) : (
            <div ref={feedRef} style={{ display: "flex", flexDirection: "column", gap: "10px", padding: "10px 16px 80px" }}>
              {feed.map(look => (
                <CommunityCard
                  key={look.id} look={look}
                  isSaved={savedIds.has(look.id)}
                  onTap={() => setSelected(look)}
                  onSave={e => handleSave(look, e)}
                />
              ))}
            </div>
          )}
        </div>
      </div>

      <NomiNav />

      {selected && (
        <CommunityDetail
          look={looks.find(l => l.id === selected.id) ?? selected}
          isSaved={savedIds.has(selected.id)}
          onSave={e => handleSave(selected, e)}
          onClose={() => setSelected(null)}
          onTagTap={tag => { setQuery(tag); setSelected(null); }}
        />
      )}
    </>
  );
}

// ─── Community Card ───────────────────────────────────────────────────────────

function CommunityCard({ look, isSaved, onTap, onSave }: {
  look: CommunityLook; isSaved: boolean;
  onTap: () => void; onSave: (e: React.MouseEvent) => void;
}) {
  const allImages = look.images?.length ? look.images : (look.image ? [look.image] : []);
  const slots     = allImages.slice(0, 4);
  const hashTags  = look.tags.filter(t => t.startsWith("#"));
  const stores    = [...new Set(look.pieces.map(p => p.store).filter(Boolean))] as string[];
  const storeLabel = stores.length === 1 ? stores[0] : null;

  return (
    <div onClick={onTap} style={{ border: "1px solid #ebebeb", borderRadius: "16px", background: "#f7f6f3", cursor: "pointer", overflow: "hidden" }}>
      {/* Thumbnail strip — only render slots we have actual images for */}
      <div style={{ display: "flex", gap: "4px", padding: "12px 12px 8px" }}>
        {slots.map((img, i) => (
          <div key={i} style={{ flex: 1, aspectRatio: "1", borderRadius: "8px", overflow: "hidden", background: PLACEHOLDER_COLORS[i % 4] }}>
            <ItemThumbnail src={img} imageTier={look.imageTiers?.[i]} />
          </div>
        ))}
      </div>

      {/* Meta row */}
      <div style={{ padding: "0 12px 12px", display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: "8px" }}>
        <div style={{ flex: 1, minWidth: 0 }}>
          {look.caption && (
            <p style={{ fontSize: "12px", fontWeight: 600, color: "#000", letterSpacing: "-0.1px", lineHeight: 1.3, marginBottom: "3px", overflow: "hidden", whiteSpace: "nowrap", textOverflow: "ellipsis" }}>
              {look.caption}
            </p>
          )}
          <p style={{ fontSize: "11px", color: "#aaa", overflow: "hidden", whiteSpace: "nowrap", textOverflow: "ellipsis" }}>
            {look.posterName}
            {look.pieces.length > 0 ? ` · ${look.pieces.length} ${look.pieces.length === 1 ? "piece" : "pieces"}` : ""}
            {storeLabel ? ` · ${storeLabel}` : ""}
          </p>
          {hashTags.length > 0 && (
            <p style={{ fontSize: "10px", color: "#ccc", marginTop: "2px" }}>{hashTags.slice(0, 2).join(" ")}</p>
          )}
        </div>
        <button
          onClick={onSave}
          style={{ background: "none", border: "none", cursor: "pointer", padding: "2px 0", flexShrink: 0, lineHeight: 0 }}
        >
          {isSaved ? <BookmarkFillSm /> : <BookmarkOutlineSm />}
        </button>
      </div>
    </div>
  );
}

// ─── Vibe Tile ────────────────────────────────────────────────────────────────

function VibeTile({ label, image, onTap }: { label: string; image: string; onTap: () => void }) {
  return (
    <button
      onClick={onTap}
      style={{
        position: "relative", width: "100%", height: "110px",
        borderRadius: "14px", overflow: "hidden",
        border: "none", padding: 0, cursor: "pointer",
        background: "#f0ede8", display: "block",
      }}
    >
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={image} alt="" style={{ width: "100%", height: "100%", objectFit: "cover", objectPosition: "center", display: "block" }} />
      <div style={{ position: "absolute", inset: 0, background: "linear-gradient(to top, rgba(0,0,0,0.64) 0%, rgba(0,0,0,0.08) 60%, transparent 100%)" }} />
      <span style={{
        position: "absolute", bottom: "10px", left: "11px", right: "8px",
        fontSize: "12px", fontWeight: 700, color: "#fff",
        letterSpacing: "-0.1px", lineHeight: 1.25,
        textAlign: "left", display: "block",
      }}>
        {label}
      </span>
    </button>
  );
}

// ─── Pinterest import ──────────────────────────────────────────────────────────

function PinterestSection() {
  const [connected,     setConnected]     = useState<boolean | null>(null); // null = still checking
  const [boards,        setBoards]        = useState<PinterestBoard[] | null>(null);
  const [selectedBoard, setSelectedBoard] = useState<PinterestBoard | null>(null);
  const [pins,          setPins]          = useState<PinterestPin[] | null>(null);
  const [loading,       setLoading]       = useState(false);
  const [loadError,     setLoadError]     = useState(false);

  useEffect(() => {
    // Clean up the OAuth redirect param so a page refresh doesn't re-show it.
    const params = new URLSearchParams(window.location.search);
    if (params.has("pinterest")) {
      window.history.replaceState({}, "", window.location.pathname);
    }
    fetch("/api/pinterest/status")
      .then(r => r.json())
      .then(d => setConnected(!!d.connected))
      .catch(() => setConnected(false));
  }, []);

  useEffect(() => {
    if (connected !== true) return;
    setLoading(true);
    setLoadError(false);
    fetch("/api/pinterest/boards")
      .then(r => r.json())
      .then(d => { if (d.boards) setBoards(d.boards); else setLoadError(true); })
      .catch(() => setLoadError(true))
      .finally(() => setLoading(false));
  }, [connected]);

  function openBoard(board: PinterestBoard) {
    setSelectedBoard(board);
    setPins(null);
    setLoading(true);
    setLoadError(false);
    fetch(`/api/pinterest/boards/${board.id}/pins`)
      .then(r => r.json())
      .then(d => { if (d.pins) setPins(d.pins); else setLoadError(true); })
      .catch(() => setLoadError(true))
      .finally(() => setLoading(false));
  }

  function disconnect() {
    fetch("/api/pinterest/disconnect", { method: "POST" }).then(() => {
      setConnected(false);
      setBoards(null);
      setSelectedBoard(null);
      setPins(null);
    });
  }

  if (connected === null) return null; // avoid a flash of the connect prompt while checking

  return (
    <div style={{ padding: "16px 16px 0" }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "10px" }}>
        <p style={{ fontSize: "13px", fontWeight: 600, color: "#000", letterSpacing: "-0.2px" }}>From Pinterest</p>
        {connected && (
          <button onClick={disconnect} style={{ fontSize: "11px", color: "#bbb", background: "none", border: "none", cursor: "pointer", textDecoration: "underline", textUnderlineOffset: "2px", fontFamily: "inherit" }}>
            Disconnect
          </button>
        )}
      </div>

      {!connected ? (
        <a href="/api/pinterest/connect" style={{
          display: "flex", alignItems: "center", justifyContent: "center", gap: "8px",
          padding: "16px", borderRadius: "14px", border: "1.5px dashed #e0dbd4",
          background: "#faf9f7", color: "#555", fontSize: "13px", fontWeight: 500,
          textDecoration: "none", marginBottom: "8px",
        }}>
          Connect Pinterest to import your boards
        </a>
      ) : selectedBoard ? (
        <div style={{ marginBottom: "8px" }}>
          <button onClick={() => { setSelectedBoard(null); setPins(null); }} style={{ fontSize: "12px", color: "#c9a96e", background: "none", border: "none", cursor: "pointer", marginBottom: "10px", padding: 0, fontFamily: "inherit" }}>
            ← All boards
          </button>
          <p style={{ fontSize: "13px", fontWeight: 600, color: "#000", marginBottom: "8px" }}>{selectedBoard.name}</p>
          {loading ? (
            <p style={{ fontSize: "12px", color: "#bbb" }}>Loading pins…</p>
          ) : loadError ? (
            <p style={{ fontSize: "12px", color: "#bbb" }}>Couldn&apos;t load pins.</p>
          ) : (pins ?? []).length === 0 ? (
            <p style={{ fontSize: "12px", color: "#bbb" }}>No pins in this board.</p>
          ) : (
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "6px" }}>
              {(pins ?? []).map(pin => (
                <a key={pin.id} href={pin.link ?? "https://www.pinterest.com/"} target="_blank" rel="noopener noreferrer"
                  style={{ aspectRatio: "1", borderRadius: "10px", overflow: "hidden", background: "#f0ede8", display: "block" }}>
                  <ItemThumbnail src={pin.image ?? undefined} />
                </a>
              ))}
            </div>
          )}
        </div>
      ) : loading ? (
        <p style={{ fontSize: "12px", color: "#bbb", marginBottom: "8px" }}>Loading boards…</p>
      ) : loadError ? (
        <p style={{ fontSize: "12px", color: "#bbb", marginBottom: "8px" }}>Couldn&apos;t load boards.</p>
      ) : (boards ?? []).length === 0 ? (
        <p style={{ fontSize: "12px", color: "#bbb", marginBottom: "8px" }}>No boards found on your Pinterest account.</p>
      ) : (
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px", marginBottom: "8px" }}>
          {(boards ?? []).map(board => (
            <button key={board.id} onClick={() => openBoard(board)} style={{ borderRadius: "16px", background: "#f7f6f3", overflow: "hidden", textAlign: "left", border: "none", cursor: "pointer", padding: 0 }}>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "2px", aspectRatio: "1", overflow: "hidden" }}>
                {[0, 1, 2, 3].map(i => (
                  <div key={i} style={{ background: PLACEHOLDER_COLORS[i], overflow: "hidden" }}>
                    {board.thumbnails[i] && <ItemThumbnail src={board.thumbnails[i]} />}
                  </div>
                ))}
              </div>
              <div style={{ padding: "10px 12px 8px" }}>
                <p style={{ fontSize: "13px", fontWeight: 600, color: "#000", letterSpacing: "-0.1px", overflow: "hidden", whiteSpace: "nowrap", textOverflow: "ellipsis" }}>{board.name}</p>
                <p style={{ fontSize: "11px", color: "#aaa" }}>{board.pinCount} {board.pinCount === 1 ? "pin" : "pins"}</p>
              </div>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// ─── Comments ──────────────────────────────────────────────────────────────────

type CommunityComment = { id: string; lookId: string; author: string; text: string; createdAt: number };

function loadComments(lookId: string): CommunityComment[] {
  try {
    const all: CommunityComment[] = JSON.parse(localStorage.getItem("nomi_community_comments") ?? "[]");
    return all.filter(c => c.lookId === lookId).sort((a, b) => a.createdAt - b.createdAt);
  } catch { return []; }
}

function saveComment(comment: CommunityComment) {
  try {
    const all: CommunityComment[] = JSON.parse(localStorage.getItem("nomi_community_comments") ?? "[]");
    localStorage.setItem("nomi_community_comments", JSON.stringify([...all, comment]));
  } catch { /* quota exceeded */ }
}

function CommentsSection({ lookId }: { lookId: string }) {
  const [comments, setComments] = useState<CommunityComment[]>([]);
  const [text, setText] = useState("");

  useEffect(() => {
    setComments(loadComments(lookId));
  }, [lookId]);

  function handlePost() {
    const trimmed = text.trim();
    if (!trimmed) return;
    const author = (() => {
      try { return localStorage.getItem("nomi_user_name")?.trim() || "Anonymous"; } catch { return "Anonymous"; }
    })();
    const comment: CommunityComment = {
      id: Math.random().toString(36).slice(2, 10),
      lookId, author, text: trimmed, createdAt: Date.now(),
    };
    saveComment(comment);
    setComments(prev => [...prev, comment]);
    setText("");
  }

  return (
    <div style={{ padding: "20px 20px 0" }}>
      <p style={{ fontSize: "11px", fontWeight: 600, color: "#bbb", letterSpacing: "0.7px", textTransform: "uppercase", marginBottom: "12px" }}>
        Comments{comments.length > 0 ? ` (${comments.length})` : ""}
      </p>

      {comments.length === 0 ? (
        <p style={{ fontSize: "13px", color: "#bbb", marginBottom: "16px" }}>No comments yet — be the first.</p>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: "14px", marginBottom: "16px" }}>
          {comments.map(c => (
            <div key={c.id}>
              <div style={{ display: "flex", alignItems: "baseline", gap: "8px" }}>
                <span style={{ fontSize: "13px", fontWeight: 600, color: "#000" }}>{c.author}</span>
                <span style={{ fontSize: "11px", color: "#bbb" }}>{timeAgo(c.createdAt)}</span>
              </div>
              <p style={{ fontSize: "13px", color: "#444", lineHeight: 1.5, marginTop: "2px" }}>{c.text}</p>
            </div>
          ))}
        </div>
      )}

      <div style={{ display: "flex", gap: "8px", paddingBottom: "24px" }}>
        <input
          value={text}
          onChange={e => setText(e.target.value)}
          onKeyDown={e => { if (e.key === "Enter") handlePost(); }}
          placeholder="Add a comment..."
          style={{ flex: 1, padding: "10px 14px", borderRadius: "99px", border: "1.5px solid #e8e8e8", fontSize: "13px", outline: "none", fontFamily: "inherit" }}
        />
        <button
          onClick={handlePost}
          disabled={!text.trim()}
          style={{
            padding: "10px 16px", borderRadius: "99px", border: "none",
            background: text.trim() ? "#000" : "#f0ede8",
            color: text.trim() ? "#fff" : "#bbb",
            fontSize: "13px", fontWeight: 600, cursor: text.trim() ? "pointer" : "default",
            fontFamily: "inherit", flexShrink: 0,
          }}
        >
          Post
        </button>
      </div>
    </div>
  );
}

// ─── Community Detail ─────────────────────────────────────────────────────────

function CommunityDetail({ look, isSaved, onSave, onClose, onTagTap }: {
  look: CommunityLook; isSaved: boolean;
  onSave: (e: React.MouseEvent) => void; onClose: () => void;
  onTagTap?: (tag: string) => void;
}) {
  // Prefer full images array; fall back to legacy single image
  const allImages = look.images?.length ? look.images : (look.image ? [look.image] : []);
  const isMulti   = allImages.length > 1;

  function shopPiece(piece: CommunityPiece) {
    if (piece.productLink) { window.open(piece.productLink, "_blank", "noopener"); return; }
    if (piece.searchUrl)   { window.open(piece.searchUrl, "_blank", "noopener"); return; }
    const q = encodeURIComponent([piece.name, piece.store].filter(Boolean).join(" "));
    window.open(`https://www.google.com/search?tbm=shop&q=${q}`, "_blank", "noopener");
  }

  return (
    <div style={{ position: "fixed", inset: 0, background: "#fff", zIndex: 60, display: "flex", flexDirection: "column", alignItems: "center", overflowY: "auto" }}>
      <div style={{ width: "100%", maxWidth: "420px", paddingBottom: "80px" }}>

        {/* Hero — single image or horizontal scroll strip */}
        <div style={{ position: "relative" }}>
          {isMulti ? (
            /* Horizontal image strip for multi-image looks */
            <div style={{
              display: "flex", gap: "6px", overflowX: "auto",
              padding: "0 0 0 0", scrollbarWidth: "none",
              scrollSnapType: "x mandatory",
            } as React.CSSProperties}>
              {allImages.map((img, i) => (
                <div key={i} style={{
                  flexShrink: 0, width: "78vw", maxWidth: "320px", height: "340px",
                  background: "#f0ede8", overflow: "hidden",
                  scrollSnapAlign: "start",
                  borderRadius: i === 0 ? "0 0 0 0" : "0",
                }}>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={img} alt="" style={{ width: "100%", height: "100%", objectFit: "cover", objectPosition: "top center", display: "block" }} />
                </div>
              ))}
              {/* Padding sentinel so last image can snap flush */}
              <div style={{ flexShrink: 0, width: "22vw", maxWidth: "100px" }} />
            </div>
          ) : (
            /* Single image — original hero layout */
            <div style={{ width: "100%", height: "380px", background: allImages[0] ? "#f0ede8" : "linear-gradient(160deg, #ede9e4 0%, #e2ddd7 100%)", overflow: "hidden" }}>
              {allImages[0] && (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={allImages[0]} alt="" style={{ width: "100%", height: "100%", objectFit: "cover", objectPosition: "top center", display: "block" }} />
              )}
              <div style={{ position: "absolute", inset: 0, background: "linear-gradient(to top, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.0) 50%)" }} />
            </div>
          )}

          {/* Floating controls — always on top */}
          <div style={{ position: "absolute", top: 0, left: 0, right: 0, display: "flex", justifyContent: "space-between", padding: "20px", pointerEvents: "none" }}>
            <button onClick={onClose} style={{ ...floatBtn, pointerEvents: "auto" }}><BackArrow /></button>
            <button onClick={onSave} style={{ ...floatBtn, pointerEvents: "auto" }}>
              {isSaved ? <BookmarkFillSm /> : <BookmarkOutlineSm />}
            </button>
          </div>

          {/* Dot indicators for multi-image */}
          {isMulti && (
            <div style={{ display: "flex", justifyContent: "center", gap: "5px", padding: "8px 0 0" }}>
              {allImages.map((_, i) => (
                <div key={i} style={{ width: "5px", height: "5px", borderRadius: "50%", background: i === 0 ? "#000" : "#ddd" }} />
              ))}
            </div>
          )}
        </div>

        {/* Poster info */}
        <div style={{ padding: "18px 20px 0" }}>
          <p style={{ fontSize: "15px", fontWeight: 600, color: "#000", letterSpacing: "-0.2px" }}>{look.posterName}</p>
          <p style={{ fontSize: "12px", color: "#aaa", marginTop: "3px" }}>{timeAgo(look.sharedAt)}</p>
          {look.caption && (
            <p style={{ fontSize: "14px", color: "#555", lineHeight: 1.65, marginTop: "10px", fontStyle: "italic" }}>
              &ldquo;{look.caption}&rdquo;
            </p>
          )}
          {/* Hashtag pills */}
          {look.tags.filter(t => t.startsWith("#")).length > 0 && (
            <div style={{ display: "flex", flexWrap: "wrap", gap: "6px", marginTop: "12px" }}>
              {look.tags.filter(t => t.startsWith("#")).map(tag => (
                <button
                  key={tag}
                  onClick={() => onTagTap?.(tag)}
                  style={{
                    padding: "4px 11px", borderRadius: "99px",
                    border: "1px solid #e0dbd4", background: "none",
                    fontSize: "12px", color: "#aaa", cursor: onTagTap ? "pointer" : "default",
                    fontFamily: "inherit", transition: "color 0.15s, border-color 0.15s",
                  }}
                  onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.color = "#c9a96e"; (e.currentTarget as HTMLButtonElement).style.borderColor = "#c9a96e"; }}
                  onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.color = "#aaa"; (e.currentTarget as HTMLButtonElement).style.borderColor = "#e0dbd4"; }}
                >
                  {tag}
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Shop this look — compact rows */}
        {look.pieces.length > 0 && (
          <div style={{ padding: "16px 20px 0" }}>
            <p style={{ fontSize: "11px", fontWeight: 600, color: "#bbb", letterSpacing: "0.7px", textTransform: "uppercase", marginBottom: "4px" }}>
              Shop this look
            </p>
            {look.pieces.map((piece, i) => (
              <button
                key={i}
                onClick={() => shopPiece(piece)}
                style={{
                  width: "100%", display: "flex", alignItems: "center", gap: "10px",
                  padding: "11px 0", background: "none", border: "none",
                  borderBottom: i < look.pieces.length - 1 ? "1px solid #f5f5f5" : "none",
                  cursor: "pointer", textAlign: "left",
                }}
              >
                <div style={{ flex: 1, minWidth: 0 }}>
                  <p style={{ fontSize: "13px", fontWeight: 600, color: "#000", letterSpacing: "-0.1px", overflow: "hidden", whiteSpace: "nowrap", textOverflow: "ellipsis" }}>{piece.name}</p>
                  {piece.store && <p style={{ fontSize: "11px", color: "#aaa", marginTop: "1px" }}>{piece.store}</p>}
                </div>
                {piece.price && <span style={{ fontSize: "12px", fontWeight: 600, color: "#c9a96e", flexShrink: 0 }}>{piece.price}</span>}
                <span style={{ fontSize: "12px", color: "#c9a96e", flexShrink: 0 }}>Shop →</span>
              </button>
            ))}
          </div>
        )}

        <div style={{ height: "1px", background: "#f0ede8", margin: "16px 20px 0" }} />
        <CommentsSection lookId={look.id} />
      </div>
    </div>
  );
}

// ─── Empty state ──────────────────────────────────────────────────────────────

function EmptyState({ onShare }: { onShare: () => void }) {
  return (
    <div style={{ display: "flex", flexDirection: "column", alignItems: "center", padding: "80px 32px", textAlign: "center" }}>
      <p style={{ fontSize: "18px", fontWeight: 600, letterSpacing: "-0.3px", color: "#000", marginBottom: "8px" }}>Nothing here yet.</p>
      <p style={{ fontSize: "14px", color: "#aaa", lineHeight: 1.6, marginBottom: "24px" }}>Be the first to share a look.</p>
      <button onClick={onShare} style={{ padding: "14px 32px", borderRadius: "16px", border: "none", background: "#c9a96e", color: "#fff", fontSize: "15px", fontWeight: 600, cursor: "pointer" }}>
        Share a look
      </button>
    </div>
  );
}

// ─── Shared styles ────────────────────────────────────────────────────────────

const floatBtn: React.CSSProperties = {
  width: "36px", height: "36px",
  background: "rgba(255,255,255,0.92)",
  border: "none", borderRadius: "50%",
  display: "flex", alignItems: "center", justifyContent: "center",
  cursor: "pointer",
};

// ─── Icons ────────────────────────────────────────────────────────────────────

function SearchIcon() {
  return <svg width="15" height="15" viewBox="0 0 15 15" fill="none"><circle cx="6.5" cy="6.5" r="4" stroke="currentColor" strokeWidth="1.4"/><path d="M9.5 9.5L12.5 12.5" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/></svg>;
}
function XIcon() {
  return <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M3 3l8 8M11 3l-8 8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></svg>;
}
function BookmarkOutlineSm() {
  return <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M3 2h8a.5.5 0 01.5.5v10L7 10l-4.5 2.5V2.5A.5.5 0 013 2z" stroke="#c9a96e" strokeWidth="1.3" strokeLinejoin="round"/></svg>;
}
function BookmarkFillSm() {
  return <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M3 2h8a.5.5 0 01.5.5v10L7 10l-4.5 2.5V2.5A.5.5 0 013 2z" fill="#c9a96e"/></svg>;
}
function BackArrow() {
  return <svg width="18" height="18" viewBox="0 0 18 18" fill="none"><path d="M11 3.5L6 9l5 5.5" stroke="#000" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round"/></svg>;
}
