"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import NomiNav from "../components/NomiNav";
import type { CommunityLook, CommunityPiece } from "../components/ShareToExploreModal";
import { OCCASION_GROUPS, toTagSlug, normalizeTag } from "../components/ShareToExploreModal";
import ItemThumbnail from "../components/ItemThumbnail";
import trendsRaw from "../data/trends.json";
import type { PinterestBoard } from "../api/pinterest/boards/route";
import type { PinterestPin } from "../api/pinterest/boards/[boardId]/pins/route";
import {
  getTasteProfile, getFeedbackSignals, migrateLegacyTasteProfile,
  recordTasteSignal, recordTasteSignals, extractTasteSignalsFromText,
  scoreAffinity, type TasteProfile, type FeedbackStore,
} from "../lib/tasteProfile";

// ─── Trends (static, generated by scripts/generate-trends.mjs) ───────────────

type TrendSource = { name: string; url: string | null };
type TrendItem   = { title: string; summary: string; sources: TrendSource[] };
type TrendsFile  = { generatedAt: string | null; trends: TrendItem[] };

const { generatedAt: trendsGeneratedAt, trends } = trendsRaw as TrendsFile;

function formatTrendDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

// ─── For You (live, taste-personalized picks) ────────────────────────────────

type ForYouPick = {
  kind: "match" | "different"; reason: string; item: string; displayName: string; url: string;
  image?: string | null; imageTier?: "confident" | "broad" | null;
};

const FOR_YOU_CACHE_KEY    = "nomi_for_you_cache";
const FOR_YOU_REFRESH_KEY  = "nomi_for_you_last_manual_refresh";
const FOR_YOU_MIN_REFRESH_MS = 60 * 60 * 1000; // 1 hour between manual refreshes

function todayKey(): string {
  return new Date().toISOString().slice(0, 10);
}

function scoreLook(look: CommunityLook, profile: TasteProfile, feedback: FeedbackStore): number {
  let score = scoreAffinity({ tags: look.tags.map(normalizeTag) }, profile, feedback);
  look.pieces.forEach(p => {
    score += scoreAffinity({ category: p.category, store: p.store }, profile, feedback);
  });
  return score;
}

/** Short "why this" line for a look — the highest-count tag/category it shares with the taste profile. */
function lookReason(look: CommunityLook, profile: TasteProfile): string | null {
  const aesthetics = profile.aesthetics ?? {};
  const categories = profile.categories ?? {};
  const topTag = look.tags
    .map(normalizeTag)
    .filter(t => aesthetics[t])
    .sort((a, b) => aesthetics[b] - aesthetics[a])[0];
  if (topTag) return `Matches your ${topTag} saves`;
  const topCategory = look.pieces
    .map(p => p.category)
    .filter((c): c is string => !!c && !!categories[c])
    .sort((a, b) => categories[b] - categories[a])[0];
  if (topCategory) return `Matches your ${topCategory} saves`;
  return null;
}

function computeTrendingTags(looks: CommunityLook[]): string[] {
  const counts: Record<string, number> = {};
  looks.forEach(l => {
    l.tags.forEach(t => {
      const n = normalizeTag(t);
      if (n) counts[n] = (counts[n] ?? 0) + 1;
    });
  });
  return Object.entries(counts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10)
    .map(([tag]) => tag);
}

// ─── Constants ────────────────────────────────────────────────────────────────

const FILTER_TABS = ["All", "OOTD", "Going out", "Events", "Weddings", "Work", "Secondhand"] as const;
type FilterTab = typeof FILTER_TABS[number];

function tabLabel(tab: FilterTab): string {
  if (tab === "All") return "All";
  const camel = tab.replace(/\s+(.)/g, (_, c) => c.toUpperCase());
  return `#${camel}`;
}

const _g = (label: string) =>
  OCCASION_GROUPS.find(g => g.label === label)!.options.map(normalizeTag);

const OCCASION_FILTER: Record<string, string[]> = {
  "OOTD":       _g("Everyday"),
  "Going out":  _g("Going out"),
  "Events":     _g("Events"),
  "Weddings":   _g("Weddings"),
  "Work":       _g("Work"),
  "Secondhand": _g("Secondhand"),
};

const OCCASION_SLUG_SET = new Set(
  OCCASION_GROUPS.flatMap(g => g.options.map(normalizeTag))
);

function slugToFilterTab(slug: string): FilterTab | null {
  const norm = normalizeTag(slug);
  for (const [tab, slugs] of Object.entries(OCCASION_FILTER)) {
    if (slugs.includes(norm)) return tab as FilterTab;
  }
  return null;
}

const PLACEHOLDER_COLORS = ["#f0ede8", "#ece9e4", "#e8e4dd", "#ede9e3"];

// ─── Helpers ─────────────────────────────────────────────────────────────────

function timeAgo(ts: number): string {
  const d = Date.now() - ts;
  const m = Math.floor(d / 60000);
  if (m < 2)  return "just now";
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  const days = Math.floor(h / 24);
  if (days < 7) return `${days}d ago`;
  return new Date(ts).toLocaleDateString([], { month: "short", day: "numeric" });
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function ExplorePage() {
  const router = useRouter();
  const [looks,     setLooks]     = useState<CommunityLook[]>([]);
  const [savedIds,  setSavedIds]  = useState<Set<string>>(new Set());
  const [activeTab, setActiveTab] = useState<FilterTab>("All");
  const [selected,  setSelected]  = useState<CommunityLook | null>(null);
  const [query,     setQuery]     = useState("");
  const feedRef = useRef<HTMLDivElement>(null);

  const [tasteProfile, setTasteProfile] = useState<TasteProfile>({});
  const [feedback,     setFeedback]     = useState<FeedbackStore>({});
  const [forYouPicks,   setForYouPicks]   = useState<ForYouPick[] | null>(null);
  const [forYouLoading, setForYouLoading] = useState(false);
  const [forYouError,   setForYouError]   = useState(false);
  const [canManualRefresh, setCanManualRefresh] = useState(true);

  function fetchForYou(trendingTags: string[], manual: boolean) {
    setForYouLoading(true);
    setForYouError(false);
    const profile  = getTasteProfile();
    const fb       = getFeedbackSignals();
    fetch("/api/for-you", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ tasteProfile: profile, feedbackSignals: fb, trendingTags }),
    })
      .then(r => r.json())
      .then(d => {
        if (!d.picks) { setForYouError(true); return; }
        setForYouPicks(d.picks);
        localStorage.setItem(FOR_YOU_CACHE_KEY, JSON.stringify({ date: todayKey(), picks: d.picks }));
        if (manual) {
          localStorage.setItem(FOR_YOU_REFRESH_KEY, String(Date.now()));
          setCanManualRefresh(false);
        }
      })
      .catch(() => setForYouError(true))
      .finally(() => setForYouLoading(false));
  }

  useEffect(() => {
    migrateLegacyTasteProfile();
    setTasteProfile(getTasteProfile());
    setFeedback(getFeedbackSignals());

    const lastManual = Number(localStorage.getItem(FOR_YOU_REFRESH_KEY) ?? 0);
    setCanManualRefresh(Date.now() - lastManual > FOR_YOU_MIN_REFRESH_MS);

    const cacheRaw = localStorage.getItem(FOR_YOU_CACHE_KEY);
    const cache = cacheRaw ? JSON.parse(cacheRaw) as { date: string; picks: ForYouPick[] } : null;
    if (cache && cache.date === todayKey()) {
      setForYouPicks(cache.picks);
    } else {
      const existingLooks: CommunityLook[] = JSON.parse(localStorage.getItem("nomi_community_looks") ?? "[]");
      fetchForYou(computeTrendingTags(existingLooks), false);
    }
  }, []);

  useEffect(() => {
    const communityLooks: CommunityLook[] = JSON.parse(localStorage.getItem("nomi_community_looks") ?? "[]");

    // One-time migration: old community looks were saved before `look.images` was added to the
    // schema and only have the single `look.image` field. Find each one's corresponding saved
    // look by matching piece names and pull the real per-item image URLs from there.
    type SavedItem = { name?: string; image?: string; isOriginal?: boolean };
    type SavedLookRef = { items: SavedItem[] };
    const savedLooks: SavedLookRef[] = JSON.parse(localStorage.getItem("nomi_saved_looks") ?? "[]");

    let anyPatched = false;
    const patched = communityLooks.map(look => {
      if (look.images?.length) return look; // already has images — nothing to do

      // Find a saved look whose non-original items match this community look's pieces exactly
      const matched = savedLooks.find(sl => {
        const saveMatchNames = sl.items.filter(i => !i.isOriginal).map(i => i.name ?? "");
        return look.pieces.length > 0 &&
               look.pieces.length <= saveMatchNames.length &&
               look.pieces.every(p => saveMatchNames.includes(p.name));
      });
      if (!matched) return look;

      const originalImg = matched.items.find(i => i.isOriginal)?.image;
      const matchImgs   = look.pieces
        .map(p => matched.items.find(i => !i.isOriginal && i.name === p.name)?.image)
        .filter((img): img is string => !!img);

      const allImgs = [originalImg, ...matchImgs].filter((img): img is string => !!img);
      if (!allImgs.length) return look;

      anyPatched = true;
      return { ...look, images: allImgs };
    });

    if (anyPatched) {
      localStorage.setItem("nomi_community_looks", JSON.stringify(patched));
    }

    setLooks(patched);
    setSavedIds(new Set(JSON.parse(localStorage.getItem("nomi_community_saved") ?? "[]")));
  }, []);

  // Ranked by closeness to taste profile + feedback, tie-broken by recency —
  // replaces pure chronological order now that Explore isn't a social feed.
  const rankedLooks = useMemo(() => {
    return [...looks].sort((a, b) => {
      const diff = scoreLook(b, tasteProfile, feedback) - scoreLook(a, tasteProfile, feedback);
      return diff !== 0 ? diff : b.sharedAt - a.sharedAt;
    });
  }, [looks, tasteProfile, feedback]);

  const feed = useMemo(() => {
    let list = [...rankedLooks];
    if (activeTab !== "All") {
      const match = OCCASION_FILTER[activeTab] ?? [];
      list = list.filter(l => l.tags.some(t => match.includes(normalizeTag(t))));
    }
    if (query.trim()) {
      const q    = query.toLowerCase();
      const qTag = q.startsWith("#") ? q : `#${q}`;
      list = list.filter(l =>
        l.caption.toLowerCase().includes(q) ||
        l.tags.some(t => t.toLowerCase().includes(q) || t.toLowerCase() === qTag) ||
        l.pieces.some(p => p.name.toLowerCase().includes(q))
      );
    }
    return list;
  }, [rankedLooks, activeTab, query]);

  const trendingTags = useMemo(() => computeTrendingTags(looks), [looks]);

  const vibeTiles = useMemo(() => {
    return OCCASION_GROUPS.flatMap(g => [...g.options])
      .map(opt => {
        const slug = normalizeTag(opt);
        const cover = looks
          .filter(l => l.tags.some(t => normalizeTag(t) === slug) && !!l.image)
          .sort((a, b) => b.sharedAt - a.sharedAt)[0];
        return cover ? { label: opt, slug, image: cover.image! } : null;
      })
      .filter((t): t is NonNullable<typeof t> => t !== null);
  }, [looks]);

  const moreLikeYourSaves = useMemo(
    () => rankedLooks.filter(l => !!(l.images?.length || l.image)).slice(0, 8),
    [rankedLooks]
  );

  function handleVibeTap(slug: string) {
    const tab = slugToFilterTab(slug);
    if (!tab) return;
    setActiveTab(tab);
    setTimeout(() => feedRef.current?.scrollIntoView({ behavior: "smooth" }), 50);
  }


  function handleSave(look: CommunityLook, e: React.MouseEvent) {
    e.stopPropagation();
    const isSaved = savedIds.has(look.id);
    setSavedIds(prev => {
      const next = new Set(prev);
      if (isSaved) {
        next.delete(look.id);
      } else {
        next.add(look.id);
        // Increment savedCount on the stored look
        const all: CommunityLook[] = JSON.parse(localStorage.getItem("nomi_community_looks") ?? "[]");
        const updated = all.map(l => l.id === look.id ? { ...l, savedCount: l.savedCount + 1 } : l);
        localStorage.setItem("nomi_community_looks", JSON.stringify(updated));
        setLooks(updated);
        // Update taste profile silently
        updateTasteProfile(look);
      }
      localStorage.setItem("nomi_community_saved", JSON.stringify([...next]));
      return next;
    });
  }

  function updateTasteProfile(look: CommunityLook) {
    let latest = tasteProfile;
    look.tags.forEach(tag => { latest = recordTasteSignal({ aesthetic: normalizeTag(tag) }); });
    look.pieces.forEach(piece => { if (piece.category) latest = recordTasteSignal({ category: piece.category }); });
    setTasteProfile(latest);
  }

  return (
    <>
      <div style={{ minHeight: "100vh", background: "#fff", display: "flex", flexDirection: "column", alignItems: "center" }}>
        <div style={{ width: "100%", maxWidth: "420px" }}>

          {/* ── Sticky header ── */}
          <div style={{ position: "sticky", top: 0, background: "#fff", zIndex: 10 }}>
            <div style={{ padding: "20px 16px 10px" }}>
              <h1 style={{ fontSize: "22px", fontWeight: 600, letterSpacing: "-0.5px", marginBottom: "12px" }}>Explore</h1>
              {/* Search */}
              <div style={{ position: "relative" }}>
                <div style={{ position: "absolute", left: "13px", top: "50%", transform: "translateY(-50%)", color: "#aaa", pointerEvents: "none", lineHeight: 0 }}>
                  <SearchIcon />
                </div>
                <input
                  type="text" placeholder="Search looks, occasions, items..."
                  value={query} onChange={e => setQuery(e.target.value)}
                  style={{ width: "100%", padding: "11px 36px 11px 38px", borderRadius: "14px", border: `1.5px solid ${query ? "#000" : "#e8e8e8"}`, fontSize: "14px", color: "#000", background: "#f7f6f3", outline: "none", transition: "border-color 0.15s", boxSizing: "border-box" } as React.CSSProperties}
                />
                {query && (
                  <button onClick={() => setQuery("")} style={{ position: "absolute", right: "12px", top: "50%", transform: "translateY(-50%)", background: "none", border: "none", cursor: "pointer", color: "#aaa", lineHeight: 0, padding: 0 }}>
                    <XIcon />
                  </button>
                )}
              </div>
            </div>
            <div style={{ display: "flex", gap: "8px", overflowX: "auto", paddingLeft: "16px", paddingRight: "16px", paddingBottom: "12px", scrollbarWidth: "none" }}>
              {FILTER_TABS.map(tab => {
                const on = activeTab === tab;
                return (
                  <button key={tab} onClick={() => setActiveTab(tab)} style={{
                    flexShrink: 0, padding: "7px 16px", borderRadius: "99px", border: "none",
                    background: on ? "#c9a96e" : "#f0ede8",
                    color: on ? "#fff" : "#6b6b6b",
                    fontSize: "13px", fontWeight: on ? 600 : 400,
                    cursor: "pointer", whiteSpace: "nowrap",
                    transition: "background 0.15s, color 0.15s",
                  }}>
                    {tabLabel(tab)}
                  </button>
                );
              })}
            </div>
            {trendingTags.length > 0 && (
              <div>
                <p style={{ padding: "8px 16px 4px", fontSize: "10px", fontWeight: 600, color: "#bbb", letterSpacing: "0.6px", textTransform: "uppercase" }}>Trending tags</p>
                <div style={{ display: "flex", gap: "6px", overflowX: "auto", paddingLeft: "16px", paddingRight: "16px", paddingBottom: "10px", scrollbarWidth: "none" } as React.CSSProperties}>
                  {trendingTags.map(tag => {
                    const active = query.toLowerCase() === tag.toLowerCase();
                    return (
                      <button key={tag} onClick={() => setQuery(active ? "" : tag)} style={{
                        flexShrink: 0, padding: "5px 12px", borderRadius: "99px",
                        border: `1px solid ${active ? "#c9a96e" : "#e0dbd4"}`,
                        background: "none", cursor: "pointer", whiteSpace: "nowrap",
                        color: active ? "#c9a96e" : "#999",
                        fontSize: "12px", fontWeight: active ? 500 : 400,
                        transition: "color 0.15s, border-color 0.15s",
                        fontFamily: "inherit",
                      }}>
                        {tag}
                      </button>
                    );
                  })}
                </div>
              </div>
            )}
            <div style={{ height: "1px", background: "#ebebeb" }} />
          </div>

          {/* ── What's Hot ── */}
          {activeTab === "All" && trends.length > 0 && (
            <div style={{ padding: "16px 0 4px" }}>
              <div style={{ padding: "0 16px 10px" }}>
                <p style={{ fontSize: "13px", fontWeight: 600, color: "#000", letterSpacing: "-0.2px" }}>What&apos;s Hot</p>
                <p style={{ fontSize: "11px", color: "#bbb", marginTop: "2px" }}>
                  Weekly fashion digest{trendsGeneratedAt ? ` · Updated ${formatTrendDate(trendsGeneratedAt)}` : ""}
                </p>
              </div>
              <div style={{ display: "flex", gap: "10px", overflowX: "auto", paddingLeft: "16px", paddingRight: "16px", paddingBottom: "4px", scrollbarWidth: "none" } as React.CSSProperties}>
                {trends.map((trend, i) => (
                  <div key={i} style={{
                    flexShrink: 0, width: "calc(82% - 8px)",
                    borderRadius: "14px",
                    border: "1px solid #ede8e0", borderLeft: "3px solid #c9a96e",
                    background: "#faf7f3",
                    padding: "14px 14px 14px 13px",
                  }}>
                    <p style={{ fontSize: "13px", fontWeight: 600, color: "#000", letterSpacing: "-0.2px", lineHeight: 1.3 }}>{trend.title}</p>
                    <p style={{ fontSize: "12px", color: "#555", lineHeight: 1.65, marginTop: "7px" }}>{trend.summary}</p>
                    <p style={{ fontSize: "11px", color: "#bbb", marginTop: "9px" }}>
                      via{" "}
                      {trend.sources.map((src, j) => (
                        <span key={j}>
                          {j > 0 && ", "}
                          {src.url
                            ? <a href={src.url} target="_blank" rel="noopener noreferrer" style={{ color: "#bbb", textDecoration: "underline", textUnderlineOffset: "2px" }}>{src.name}</a>
                            : src.name
                          }
                        </span>
                      ))}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* ── For You ── */}
          {activeTab === "All" && (forYouLoading || forYouPicks?.length) ? (
            <div style={{ padding: "18px 16px 0" }}>
              <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between", marginBottom: "2px" }}>
                <p style={{ fontSize: "13px", fontWeight: 600, color: "#000", letterSpacing: "-0.2px" }}>For you</p>
                <button
                  onClick={() => canManualRefresh && fetchForYou(trendingTags, true)}
                  disabled={!canManualRefresh || forYouLoading}
                  style={{ background: "none", border: "none", padding: 0, fontSize: "11px", cursor: canManualRefresh && !forYouLoading ? "pointer" : "default", color: canManualRefresh && !forYouLoading ? "#c9a96e" : "#ccc", fontFamily: "inherit" }}
                >
                  {forYouLoading ? "Refreshing…" : "Refresh picks"}
                </button>
              </div>
              <p style={{ fontSize: "11px", color: "#bbb", margin: "0 0 10px" }}>Based on your taste and saves</p>
              {forYouLoading && !forYouPicks ? (
                <p style={{ fontSize: "12px", color: "#bbb" }}>Finding picks for you…</p>
              ) : forYouError && !forYouPicks ? (
                <p style={{ fontSize: "12px", color: "#bbb" }}>Couldn&apos;t load picks — try again shortly.</p>
              ) : (
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px", marginBottom: "8px" }}>
                  {(forYouPicks ?? []).map((pick, i) => (
                    <a key={i} href={pick.url} target="_blank" rel="noopener noreferrer" style={{ border: "1px solid #ebebeb", borderRadius: "14px", background: "#f7f6f3", overflow: "hidden", textDecoration: "none", display: "block" }}>
                      <div style={{ aspectRatio: "1", background: PLACEHOLDER_COLORS[i % 4] }}>
                        <ItemThumbnail src={pick.image ?? undefined} imageTier={pick.imageTier} />
                      </div>
                      <div style={{ padding: "8px 10px" }}>
                        <p style={{ fontSize: "11px", fontWeight: 600, color: "#000", margin: "0 0 3px", overflow: "hidden", whiteSpace: "nowrap", textOverflow: "ellipsis" }}>
                          {pick.item} · {pick.displayName}
                        </p>
                        <p style={{ fontSize: "10px", color: pick.kind === "different" ? "#999" : "#c9a96e", margin: 0 }}>{pick.reason}</p>
                      </div>
                    </a>
                  ))}
                </div>
              )}
            </div>
          ) : null}

          {/* ── Pinterest → taste signal (no browsing UI; just improves For you) ── */}
          {activeTab === "All" && <PinterestConnect onTasteUpdated={() => fetchForYou(trendingTags, false)} />}

          {/* ── More like your saves ── */}
          {activeTab === "All" && moreLikeYourSaves.length > 0 && (
            <div style={{ padding: "18px 16px 0" }}>
              <p style={{ fontSize: "13px", fontWeight: 600, color: "#000", letterSpacing: "-0.2px", marginBottom: "10px" }}>More like your saves</p>
              <div style={{ display: "flex", gap: "8px", overflowX: "auto", paddingBottom: "2px", scrollbarWidth: "none" } as React.CSSProperties}>
                {moreLikeYourSaves.map(look => {
                  const thumb = look.images?.[0] ?? look.image;
                  return (
                    <button key={look.id} onClick={() => setSelected(look)} style={{ flexShrink: 0, width: "76px", height: "76px", borderRadius: "10px", overflow: "hidden", background: "#f0ede8", border: "none", padding: 0, cursor: "pointer" }}>
                      {thumb && <ItemThumbnail src={thumb} />}
                    </button>
                  );
                })}
              </div>
            </div>
          )}

          {/* ── Browse by vibe ── */}
          {activeTab === "All" && vibeTiles.length > 0 && (
            <div style={{ padding: "16px 16px 0" }}>
              <p style={{ fontSize: "13px", fontWeight: 600, color: "#000", letterSpacing: "-0.2px", marginBottom: "10px" }}>Browse by vibe</p>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px", marginBottom: "8px" }}>
                {vibeTiles.map(tile => (
                  <VibeTile key={tile.slug} label={tile.label} image={tile.image} onTap={() => handleVibeTap(tile.slug)} />
                ))}
              </div>
            </div>
          )}

          {/* ── Feed ── */}
          {looks.length === 0 ? (
            <EmptyState onShare={() => router.push("/saved")} />
          ) : feed.length === 0 ? (
            <div style={{ display: "flex", flexDirection: "column", alignItems: "center", padding: "60px 32px", textAlign: "center", gap: "10px" }}>
              <p style={{ fontSize: "15px", color: "#555" }}>No looks found for that search.</p>
              <button onClick={() => setQuery("")} style={{ background: "none", border: "none", cursor: "pointer", color: "#c9a96e", fontSize: "14px", fontWeight: 500, padding: 0 }}>Clear search</button>
            </div>
          ) : (
            <div ref={feedRef} style={{ padding: "18px 16px 80px" }}>
              <p style={{ fontSize: "13px", fontWeight: 600, color: "#000", letterSpacing: "-0.2px", marginBottom: "10px" }}>Your picks</p>
              <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                {feed.map(look => (
                  <CommunityCard
                    key={look.id} look={look}
                    isSaved={savedIds.has(look.id)}
                    onTap={() => setSelected(look)}
                    onSave={e => handleSave(look, e)}
                    reason={lookReason(look, tasteProfile)}
                  />
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      <NomiNav />

      {selected && (
        <CommunityDetail
          look={looks.find(l => l.id === selected.id) ?? selected}
          isSaved={savedIds.has(selected.id)}
          onSave={e => handleSave(selected, e)}
          onClose={() => setSelected(null)}
          onTagTap={tag => { setQuery(tag); setSelected(null); }}
        />
      )}
    </>
  );
}

// ─── Community Card ───────────────────────────────────────────────────────────

function CommunityCard({ look, isSaved, onTap, onSave, reason }: {
  look: CommunityLook; isSaved: boolean;
  onTap: () => void; onSave: (e: React.MouseEvent) => void;
  reason?: string | null;
}) {
  const allImages = look.images?.length ? look.images : (look.image ? [look.image] : []);
  const slots     = allImages.slice(0, 4);
  const hashTags  = look.tags.filter(t => t.startsWith("#"));
  const stores    = [...new Set(look.pieces.map(p => p.store).filter(Boolean))] as string[];
  const storeLabel = stores.length === 1 ? stores[0] : null;
  const metaLine = reason ?? [
    look.pieces.length > 0 ? `${look.pieces.length} ${look.pieces.length === 1 ? "piece" : "pieces"}` : "",
    storeLabel ?? "",
  ].filter(Boolean).join(" · ");

  return (
    <div onClick={onTap} style={{ border: "1px solid #ebebeb", borderRadius: "16px", background: "#f7f6f3", cursor: "pointer", overflow: "hidden" }}>
      {/* Thumbnail strip — only render slots we have actual images for */}
      <div style={{ display: "flex", gap: "4px", padding: "12px 12px 8px" }}>
        {slots.map((img, i) => (
          <div key={i} style={{ flex: 1, aspectRatio: "1", borderRadius: "8px", overflow: "hidden", background: PLACEHOLDER_COLORS[i % 4] }}>
            <ItemThumbnail src={img} imageTier={look.imageTiers?.[i]} />
          </div>
        ))}
      </div>

      {/* Meta row */}
      <div style={{ padding: "0 12px 12px", display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: "8px" }}>
        <div style={{ flex: 1, minWidth: 0 }}>
          {look.caption && (
            <p style={{ fontSize: "12px", fontWeight: 600, color: "#000", letterSpacing: "-0.1px", lineHeight: 1.3, marginBottom: "3px", overflow: "hidden", whiteSpace: "nowrap", textOverflow: "ellipsis" }}>
              {look.caption}
            </p>
          )}
          {metaLine && (
            <p style={{ fontSize: "11px", color: reason ? "#c9a96e" : "#aaa", overflow: "hidden", whiteSpace: "nowrap", textOverflow: "ellipsis" }}>
              {metaLine}
            </p>
          )}
          {hashTags.length > 0 && (
            <p style={{ fontSize: "10px", color: "#ccc", marginTop: "2px" }}>{hashTags.slice(0, 2).join(" ")}</p>
          )}
        </div>
        <button
          onClick={onSave}
          style={{ background: "none", border: "none", cursor: "pointer", padding: "2px 0", flexShrink: 0, lineHeight: 0 }}
        >
          {isSaved ? <BookmarkFillSm /> : <BookmarkOutlineSm />}
        </button>
      </div>
    </div>
  );
}

// ─── Vibe Tile ────────────────────────────────────────────────────────────────

function VibeTile({ label, image, onTap }: { label: string; image: string; onTap: () => void }) {
  return (
    <button
      onClick={onTap}
      style={{
        position: "relative", width: "100%", height: "110px",
        borderRadius: "14px", overflow: "hidden",
        border: "none", padding: 0, cursor: "pointer",
        background: "#f0ede8", display: "block",
      }}
    >
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={image} alt="" style={{ width: "100%", height: "100%", objectFit: "cover", objectPosition: "center", display: "block" }} />
      <div style={{ position: "absolute", inset: 0, background: "linear-gradient(to top, rgba(0,0,0,0.64) 0%, rgba(0,0,0,0.08) 60%, transparent 100%)" }} />
      <span style={{
        position: "absolute", bottom: "10px", left: "11px", right: "8px",
        fontSize: "12px", fontWeight: 700, color: "#fff",
        letterSpacing: "-0.1px", lineHeight: 1.25,
        textAlign: "left", display: "block",
      }}>
        {label}
      </span>
    </button>
  );
}

// ─── Pinterest import ──────────────────────────────────────────────────────────

// Scores each board/pin's text into the taste profile at most once ever (tracked
// by id in localStorage) so re-opening Explore doesn't re-count the same boards
// every visit and skew the profile toward whatever's on Pinterest.
function scoreOnce(storageKey: string, ids: string[], texts: string[]): boolean {
  if (!ids.length) return false;
  let seen: Set<string>;
  try { seen = new Set(JSON.parse(localStorage.getItem(storageKey) ?? "[]")); } catch { seen = new Set(); }
  const freshIdx = ids.map((id, i) => (seen.has(id) ? -1 : i)).filter(i => i >= 0);
  if (!freshIdx.length) return false;
  const signals = freshIdx.flatMap(i => extractTasteSignalsFromText(texts[i]));
  if (signals.length) recordTasteSignals(signals);
  freshIdx.forEach(i => seen.add(ids[i]));
  try { localStorage.setItem(storageKey, JSON.stringify([...seen])); } catch { /* quota */ }
  return signals.length > 0;
}

// No board/pin browsing UI — connecting only feeds board names, descriptions,
// and pin titles into the taste profile in the background so "For you" gets
// better. Runs once per newly-seen board/pin (scoreOnce dedupes by id), and
// only pings the parent to regenerate "For you" if something new was found.
function PinterestConnect({ onTasteUpdated }: { onTasteUpdated: () => void }) {
  const [connected, setConnected] = useState<boolean | null>(null); // null = still checking
  const [syncing,   setSyncing]   = useState(false);
  const notifiedRef = useRef(false); // at most one For-you refresh per mount

  // ExplorePage passes a fresh `onTasteUpdated` closure every render (it closes
  // over trendingTags); holding it in a ref instead of the effect's dep array
  // keeps the boards/pins fetch below from re-firing (and re-hitting the
  // Pinterest API) on every unrelated parent re-render.
  const onTasteUpdatedRef = useRef(onTasteUpdated);
  useEffect(() => { onTasteUpdatedRef.current = onTasteUpdated; }, [onTasteUpdated]);

  useEffect(() => {
    // Clean up the OAuth redirect param so a page refresh doesn't re-show it.
    const params = new URLSearchParams(window.location.search);
    if (params.has("pinterest")) {
      window.history.replaceState({}, "", window.location.pathname);
    }
    fetch("/api/pinterest/status")
      .then(r => r.json())
      .then(d => setConnected(!!d.connected))
      .catch(() => setConnected(false));
  }, []);

  useEffect(() => {
    if (connected !== true) return;
    setSyncing(true);
    fetch("/api/pinterest/boards")
      .then(r => r.json())
      .then(async d => {
        const boards: PinterestBoard[] = d.boards ?? [];
        if (!boards.length) return;
        let updated = scoreOnce(
          "nomi_pinterest_boards_scored",
          boards.map(b => b.id),
          boards.map(b => `${b.name} ${b.description ?? ""}`)
        );

        const pinResults = await Promise.allSettled(
          boards.map(b => fetch(`/api/pinterest/boards/${b.id}/pins`).then(r => r.json()))
        );
        pinResults.forEach(r => {
          if (r.status !== "fulfilled") return;
          const pins: PinterestPin[] = r.value.pins ?? [];
          if (!pins.length) return;
          const pinsUpdated = scoreOnce(
            "nomi_pinterest_pins_scored",
            pins.map(p => p.id),
            pins.map(p => p.title ?? "")
          );
          updated = updated || pinsUpdated;
        });

        if (updated && !notifiedRef.current) {
          notifiedRef.current = true;
          onTasteUpdatedRef.current();
        }
      })
      .catch(() => { /* best-effort — no visible browsing UI depends on this succeeding */ })
      .finally(() => setSyncing(false));
  }, [connected]);

  function disconnect() {
    fetch("/api/pinterest/disconnect", { method: "POST" }).then(() => setConnected(false));
  }

  if (connected === null) return null; // avoid a flash of the connect prompt while checking

  return (
    <div style={{ padding: "10px 16px 0" }}>
      {!connected ? (
        <a href="/api/pinterest/connect" style={{ fontSize: "12px", color: "#c9a96e", fontWeight: 500, textDecoration: "none" }}>
          Connect Pinterest to improve your picks →
        </a>
      ) : (
        <p style={{ fontSize: "11px", color: "#bbb" }}>
          {syncing ? "Syncing Pinterest…" : "Connected to Pinterest"}
          {" · "}
          <button onClick={disconnect} style={{ fontSize: "11px", color: "#bbb", background: "none", border: "none", cursor: "pointer", textDecoration: "underline", textUnderlineOffset: "2px", padding: 0, fontFamily: "inherit" }}>
            Disconnect
          </button>
        </p>
      )}
    </div>
  );
}

// ─── Community Detail ─────────────────────────────────────────────────────────

function CommunityDetail({ look, isSaved, onSave, onClose, onTagTap }: {
  look: CommunityLook; isSaved: boolean;
  onSave: (e: React.MouseEvent) => void; onClose: () => void;
  onTagTap?: (tag: string) => void;
}) {
  // Prefer full images array; fall back to legacy single image
  const allImages = look.images?.length ? look.images : (look.image ? [look.image] : []);
  const isMulti   = allImages.length > 1;

  function shopPiece(piece: CommunityPiece) {
    if (piece.productLink) { window.open(piece.productLink, "_blank", "noopener"); return; }
    if (piece.searchUrl)   { window.open(piece.searchUrl, "_blank", "noopener"); return; }
    const q = encodeURIComponent([piece.name, piece.store].filter(Boolean).join(" "));
    window.open(`https://www.google.com/search?tbm=shop&q=${q}`, "_blank", "noopener");
  }

  return (
    <div style={{ position: "fixed", inset: 0, background: "#fff", zIndex: 60, display: "flex", flexDirection: "column", alignItems: "center", overflowY: "auto" }}>
      <div style={{ width: "100%", maxWidth: "420px", paddingBottom: "80px" }}>

        {/* Hero — single image or horizontal scroll strip */}
        <div style={{ position: "relative" }}>
          {isMulti ? (
            /* Horizontal image strip for multi-image looks */
            <div style={{
              display: "flex", gap: "6px", overflowX: "auto",
              padding: "0 0 0 0", scrollbarWidth: "none",
              scrollSnapType: "x mandatory",
            } as React.CSSProperties}>
              {allImages.map((img, i) => (
                <div key={i} style={{
                  flexShrink: 0, width: "78vw", maxWidth: "320px", height: "340px",
                  background: "#f0ede8", overflow: "hidden",
                  scrollSnapAlign: "start",
                  borderRadius: i === 0 ? "0 0 0 0" : "0",
                }}>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={img} alt="" style={{ width: "100%", height: "100%", objectFit: "cover", objectPosition: "top center", display: "block" }} />
                </div>
              ))}
              {/* Padding sentinel so last image can snap flush */}
              <div style={{ flexShrink: 0, width: "22vw", maxWidth: "100px" }} />
            </div>
          ) : (
            /* Single image — original hero layout */
            <div style={{ width: "100%", height: "380px", background: allImages[0] ? "#f0ede8" : "linear-gradient(160deg, #ede9e4 0%, #e2ddd7 100%)", overflow: "hidden" }}>
              {allImages[0] && (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={allImages[0]} alt="" style={{ width: "100%", height: "100%", objectFit: "cover", objectPosition: "top center", display: "block" }} />
              )}
              <div style={{ position: "absolute", inset: 0, background: "linear-gradient(to top, rgba(0,0,0,0.5) 0%, rgba(0,0,0,0.0) 50%)" }} />
            </div>
          )}

          {/* Floating controls — always on top */}
          <div style={{ position: "absolute", top: 0, left: 0, right: 0, display: "flex", justifyContent: "space-between", padding: "20px", pointerEvents: "none" }}>
            <button onClick={onClose} style={{ ...floatBtn, pointerEvents: "auto" }}><BackArrow /></button>
            <button onClick={onSave} style={{ ...floatBtn, pointerEvents: "auto" }}>
              {isSaved ? <BookmarkFillSm /> : <BookmarkOutlineSm />}
            </button>
          </div>

          {/* Dot indicators for multi-image */}
          {isMulti && (
            <div style={{ display: "flex", justifyContent: "center", gap: "5px", padding: "8px 0 0" }}>
              {allImages.map((_, i) => (
                <div key={i} style={{ width: "5px", height: "5px", borderRadius: "50%", background: i === 0 ? "#000" : "#ddd" }} />
              ))}
            </div>
          )}
        </div>

        {/* Caption + tags */}
        <div style={{ padding: "18px 20px 0" }}>
          <p style={{ fontSize: "12px", color: "#aaa" }}>Saved {timeAgo(look.sharedAt)}</p>
          {look.caption && (
            <p style={{ fontSize: "14px", color: "#555", lineHeight: 1.65, marginTop: "10px", fontStyle: "italic" }}>
              &ldquo;{look.caption}&rdquo;
            </p>
          )}
          {/* Hashtag pills */}
          {look.tags.filter(t => t.startsWith("#")).length > 0 && (
            <div style={{ display: "flex", flexWrap: "wrap", gap: "6px", marginTop: "12px" }}>
              {look.tags.filter(t => t.startsWith("#")).map(tag => (
                <button
                  key={tag}
                  onClick={() => onTagTap?.(tag)}
                  style={{
                    padding: "4px 11px", borderRadius: "99px",
                    border: "1px solid #e0dbd4", background: "none",
                    fontSize: "12px", color: "#aaa", cursor: onTagTap ? "pointer" : "default",
                    fontFamily: "inherit", transition: "color 0.15s, border-color 0.15s",
                  }}
                  onMouseEnter={e => { (e.currentTarget as HTMLButtonElement).style.color = "#c9a96e"; (e.currentTarget as HTMLButtonElement).style.borderColor = "#c9a96e"; }}
                  onMouseLeave={e => { (e.currentTarget as HTMLButtonElement).style.color = "#aaa"; (e.currentTarget as HTMLButtonElement).style.borderColor = "#e0dbd4"; }}
                >
                  {tag}
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Shop this look — compact rows */}
        {look.pieces.length > 0 && (
          <div style={{ padding: "16px 20px 0" }}>
            <p style={{ fontSize: "11px", fontWeight: 600, color: "#bbb", letterSpacing: "0.7px", textTransform: "uppercase", marginBottom: "4px" }}>
              Shop this look
            </p>
            {look.pieces.map((piece, i) => (
              <button
                key={i}
                onClick={() => shopPiece(piece)}
                style={{
                  width: "100%", display: "flex", alignItems: "center", gap: "10px",
                  padding: "11px 0", background: "none", border: "none",
                  borderBottom: i < look.pieces.length - 1 ? "1px solid #f5f5f5" : "none",
                  cursor: "pointer", textAlign: "left",
                }}
              >
                <div style={{ flex: 1, minWidth: 0 }}>
                  <p style={{ fontSize: "13px", fontWeight: 600, color: "#000", letterSpacing: "-0.1px", overflow: "hidden", whiteSpace: "nowrap", textOverflow: "ellipsis" }}>{piece.name}</p>
                  {piece.store && <p style={{ fontSize: "11px", color: "#aaa", marginTop: "1px" }}>{piece.store}</p>}
                </div>
                {piece.price && <span style={{ fontSize: "12px", fontWeight: 600, color: "#c9a96e", flexShrink: 0 }}>{piece.price}</span>}
                <span style={{ fontSize: "12px", color: "#c9a96e", flexShrink: 0 }}>Shop →</span>
              </button>
            ))}
          </div>
        )}

      </div>
    </div>
  );
}

// ─── Empty state ──────────────────────────────────────────────────────────────

function EmptyState({ onShare }: { onShare: () => void }) {
  return (
    <div style={{ display: "flex", flexDirection: "column", alignItems: "center", padding: "80px 32px", textAlign: "center" }}>
      <p style={{ fontSize: "18px", fontWeight: 600, letterSpacing: "-0.3px", color: "#000", marginBottom: "8px" }}>No picks yet.</p>
      <p style={{ fontSize: "14px", color: "#aaa", lineHeight: 1.6, marginBottom: "24px" }}>Save a few looks to get personalized picks here.</p>
      <button onClick={onShare} style={{ padding: "14px 32px", borderRadius: "16px", border: "none", background: "#c9a96e", color: "#fff", fontSize: "15px", fontWeight: 600, cursor: "pointer" }}>
        Go to Saved
      </button>
    </div>
  );
}

// ─── Shared styles ────────────────────────────────────────────────────────────

const floatBtn: React.CSSProperties = {
  width: "36px", height: "36px",
  background: "rgba(255,255,255,0.92)",
  border: "none", borderRadius: "50%",
  display: "flex", alignItems: "center", justifyContent: "center",
  cursor: "pointer",
};

// ─── Icons ────────────────────────────────────────────────────────────────────

function SearchIcon() {
  return <svg width="15" height="15" viewBox="0 0 15 15" fill="none"><circle cx="6.5" cy="6.5" r="4" stroke="currentColor" strokeWidth="1.4"/><path d="M9.5 9.5L12.5 12.5" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/></svg>;
}
function XIcon() {
  return <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M3 3l8 8M11 3l-8 8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></svg>;
}
function BookmarkOutlineSm() {
  return <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M3 2h8a.5.5 0 01.5.5v10L7 10l-4.5 2.5V2.5A.5.5 0 013 2z" stroke="#c9a96e" strokeWidth="1.3" strokeLinejoin="round"/></svg>;
}
function BookmarkFillSm() {
  return <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M3 2h8a.5.5 0 01.5.5v10L7 10l-4.5 2.5V2.5A.5.5 0 013 2z" fill="#c9a96e"/></svg>;
}
function BackArrow() {
  return <svg width="18" height="18" viewBox="0 0 18 18" fill="none"><path d="M11 3.5L6 9l5 5.5" stroke="#000" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round"/></svg>;
}
